config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  delete :logout, to: 'sessions#destroy'

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true do
      resources :answers, only: :index, shallow: true
    end

    member do
      post :start
    end

  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      # метод patch, поскольку обновляем конкретный тест - указываем опцию on: :member,
      # чтобы у нас в url был id конкретного теста

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end

  resources :gists, only: %i[index show]

  namespace :admin do
    resources :users, only: %i[index show]
  end

  namespace :admin do
    resources :gists, only: %i[index show]
  end

  namespace :admin do
    resources :badges
  end

  resources :feedbacks

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test#, optional: true
  has_many :answers, dependent: :destroy

  # scope :answers_count, -> { joins(:answers).count(:title) }
  # выдает количество записей соответствующих вопросу. так то работает, но не принято

  validates :title, presence: true

  #validate :valid_count

  # def valid_count
  #  if answers.size.to_i >= 4 then
  #    errors.add(:answers, "can be from 1 to 4")
  #  end
  # end

  # def self.count_ans
  #  joins(:answers).count(:title)
  # end

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATE = 85
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  # коллбэк нужен для того чтобы при создании объекта прохождения теста
  # первый вопрос уже имел значение, существовал для TestPassage
  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question_to_current, on: :update
  # before_validation :before_validation_build_questions_index_in_test

  def success?(rate)
    rate >= SUCCESS_RATE
  end

# проверка что успел, занесение в базу, если не успел - в базу садится false. Даже если отключил js
  def in_time?(duration)
    self.updated_at - self.created_at <= duration*60
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end
    #self.current_question = next_question
    save!
  end

  def completed?
    current_question.nil?
  end

  # def before_validation_build_questions_index_in_test
  #   questions_in_test = test.questions
  # end
  def question_number
    test.questions.where('questions.id <= ?', current_question.id).count
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question_to_current
    self.current_question = next_question if self.current_question
  end


  # получили обьект correct_answers, используем count - только тогда получаем из агрегирующего запроса количество правильных ответов
  # == справа мы используем фильтр .where(id: answer_ids) - то есть те ответы, на которые ответил пользователь.
  # Здесь answer_ids - массив, который вернули чекбоксы, которые отметил пользователь.
  def correct_answer?(answer_ids)
    if answer_ids
      correct_answers.count == (correct_answers.where(id: answer_ids).count) && correct_answers.count == answer_ids.count
    else
      correct_answers.count == 0
    end
  end

  # здесь мы используем scope :correct (определенный в модели Answer)
  # то есть выбираем только правильные ответы. Получаем обьект ActiveRecord::Relation
  # запроса к базе как такового нет.
  def correct_answers
    current_question.answers.correct
  end

  # после того как выбрали все вопросы у которых id больше чем id текущего вопроса - мы выбираем из них первый,
  # это и будет следующий вопрос. (Знак вопрос - из ранее пройденого, передаем current_question.id неявно, предотвр. sql injections)
  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]

  def show

  end

  def result

  end

  def gist
    result = GistQuestionService.new(@test_passage.current_question).call

    @created_gist_url = result.url
    gist_to_table if result

    flash_options = if result
        { notice: t('.success') }
      else
        { alert: t('.failure') }
      end
    flash[:alert] = "link_to 'Gist question', #{@created_gist_url}"


    redirect_to @test_passage, flash_options

  end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      current_user.test_list << @test_passage.test_id
      current_user.save
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist_to_table
    gist = Gist.new(user_id: current_user.id, question_id: @test_passage.current_question.id, gisturl: @created_gist_url)
    gist.save
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper

end

app/views/test_passages/result.html.erb
<h1> <%= t('.header', title: @test_passage.test.title) %>  </h1>
<% count = @test_passage.test.questions.count %>
<% correct = @test_passage.correct_questions %>
<% rate = correct*100/count %>
<% if @test_passage.success?(rate)
     color = 'green'
     message = 'passed!'
     @test_passage.update(is_finished: true)

   else
     message = 'failed...'
     color = 'red'
   end
%>

<%= link_to "All tests", tests_path %>

<h1>Pass the <%= @test_passage.test.title %> Test </h1><br/>
<h3>Count of questions in test: <%= count %></h3>
<h3>Count of correct answers in result: <%= correct %></h3>
<h3><font color="<%= color%>">Success rate: <%= rate %>%. Test <%= message %></font>


<br/><br/>

app/views/test_passages/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">

      <div class="setTestDuration" style="display: none"><%= @test_passage.test.test_duration %></div></b>
      <h1><%= t('.header', title: @test_passage.test.title) %></h1>

      <div class="countOfQuestions" style="display: none"><%= @test_passage.test.questions.count %></div>
      <div class="currentQuestionNumber" style="display: none"><%= @test_passage.question_number %></div>

  <% count = @test_passage.test.questions.count %>

  <p>Progress throught attr </p>
    <div id="progress">
      <%= content_tag :div, '', id: 'bar', data: { count: @test_passage.test.questions.count, question_index: @test_passage.question_number} %>
        <table border="2px" width="<%= count*30 %>" bordercolor="red">
          <tr>
            <td><canvas id="canvas2" width="30" height="15"></canvas></td>
          </tr>
        </table>
    </div>

    <p><%= t('.questions_count', questions_count: @test_passage.test.questions.count) %></p>
    <p><%= t('.questions_id', questions_id: @test_passage.question_number) %></p>

    <p><b><%= @test_passage.current_question.title %></b></p>

    <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
      <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false  do |b| %>
          <p><%= b.check_box id: "answer_ids_#{b.object.id}" %>
          <%= b.label %></p>
        <% end %>
      <p><%= link_to 'Gist question', gist_test_passage_path(@test_passage), method: :post %></p>
      <p><%= form.submit 'Next' %></p>
    <% end %>
    </div>
    <div class="col">
      Timer
      <%= render 'shared/timer' %>
    </div>
  </div>
</div>