config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  delete :logout, to: 'sessions#destroy'

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true do
      resources :answers, only: :index, shallow: true
    end

    member do
      post :start
    end

  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      # метод patch, поскольку обновляем конкретный тест - указываем опцию on: :member,
      # чтобы у нас в url был id конкретного теста

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end

  resources :gists, only: %i[index show]

  namespace :admin do
    resources :users, only: %i[index show]
  end

  namespace :admin do
    resources :gists, only: %i[index show]
  end

  namespace :admin do
    resources :badges
  end

  resources :feedbacks

end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true)}

  validate :answers_from_one_to_four

  def answers_from_one_to_four
    errors.add(:question, 'has so many answers') if (question.answers.count) >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord

  belongs_to :user

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order('title ASC')}

end

app/models/feedback.rb
class Feedback < ApplicationRecord

  belongs_to :user

end

app/models/gist.rb
class Gist < ApplicationRecord

  belongs_to :user
  belongs_to :question

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test#, optional: true
  has_many :answers, dependent: :destroy

  # scope :answers_count, -> { joins(:answers).count(:title) }
  # выдает количество записей соответствующих вопросу. так то работает, но не принято

  validates :title, presence: true

  #validate :valid_count

  # def valid_count
  #  if answers.size.to_i >= 4 then
  #    errors.add(:answers, "can be from 1 to 4")
  #  end
  # end

  # def self.count_ans
  #  joins(:answers).count(:title)
  # end

end

app/models/test.rb
class Test < ApplicationRecord
  max = Float::INFINITY
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages # through - опция, указывающая через какую таблица идет связь
  belongs_to :author, class_name: "User" # связь с user через author
  accepts_nested_attributes_for :questions

  #scope :levels, -> { pluck('title', 'level') }
  #scope :test_level, -> { where('title: title AND level: level')}

  scope :easy, -> { where("level < 2") }
  scope :medium, -> { where("level BETWEEN 2 AND 4") }
  scope :hard, -> { where("level BETWEEN 5 AND 9e999")}

  validates :title, presence: true
  validates :level, numericality: {only_integer: true}

  #validates :title, uniqueness: { scope: :level, message: "Test with some title and level exist!"} # заменил на ключ в базе


  def self.catsort2(catname2)
    Test.joins(:category).where(categories: {title: catname2}).order('tests.title DESC').pluck(:title)
  end

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATE = 85
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  # коллбэк нужен для того чтобы при создании объекта прохождения теста
  # первый вопрос уже имел значение, существовал для TestPassage
  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question_to_current, on: :update
  # before_validation :before_validation_build_questions_index_in_test

  def success?(rate)
    rate >= SUCCESS_RATE
  end

# проверка что успел, занесение в базу, если не успел - в базу садится false. Даже если отключил js
  def in_time?(duration)
    self.updated_at - self.created_at <= duration*60
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end
    #self.current_question = next_question
    save!
  end

  def completed?
    current_question.nil?
  end

  # def before_validation_build_questions_index_in_test
  #   questions_in_test = test.questions
  # end
  def question_number
    test.questions.where('questions.id <= ?', current_question.id).count
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question_to_current
    self.current_question = next_question if self.current_question
  end


  # получили обьект correct_answers, используем count - только тогда получаем из агрегирующего запроса количество правильных ответов
  # == справа мы используем фильтр .where(id: answer_ids) - то есть те ответы, на которые ответил пользователь.
  # Здесь answer_ids - массив, который вернули чекбоксы, которые отметил пользователь.
  def correct_answer?(answer_ids)
    if answer_ids
      correct_answers.count == (correct_answers.where(id: answer_ids).count) && correct_answers.count == answer_ids.count
    else
      correct_answers.count == 0
    end
  end

  # здесь мы используем scope :correct (определенный в модели Answer)
  # то есть выбираем только правильные ответы. Получаем обьект ActiveRecord::Relation
  # запроса к базе как такового нет.
  def correct_answers
    current_question.answers.correct
  end

  # после того как выбрали все вопросы у которых id больше чем id текущего вопроса - мы выбираем из них первый,
  # это и будет следующий вопрос. (Знак вопрос - из ранее пройденого, передаем current_question.id неявно, предотвр. sql injections)
  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

# Так как таблица называется tests_users то модель по соглашению: TestsUser (единственное число)

app/models/user.rb
# require 'digest/sha1'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  # include Auth - удаляем после подключения гема bcrypt

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages # through - опция, указывающая через какую таблица идет связь
  has_many :authored_tests, class_name: "Test", foreign_key: :author_id
  has_many :feedbacks
  has_many :badges
  # has_secure_password

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :email, uniqueness: :true

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def tests_of_user_from_level(testlevel)
    Test.joins('join user_tests on user_tests.user_id = user.id').where(user_tests: {level: testlevel})
  end

  def admin?
    self.is_a?(Admin)
  end


end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def author
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_year
    Time.now.year
  end

  def github_url(author, repo)
    link_to "Page of this project on Github", "https://github.com/#{author}/#{repo}"
  end
end

app/helpers/flash_helper.rb
module FlashHelper

  def test_flash_helper
    'it is FlashHelper'
  end

  def flash_alert
    if flash[:alert]
       content_tag :p, flash[:alert], class: 'flash alert'
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def question_header(question)
    if question.persisted?
      "Edit #{question.title} Question"
    else
      "Create New #{question.title} Question"
    end
  end



  # def question_title
  #   @question.title
  # end

  # def question_header
  #   @question.test.title
  # end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  
end

app/helpers/tests_helper.rb
module TestsHelper

  def question_count
    @tests.count
  end

  def finished?
    test.test_passage.is_finished
  end
end

app/views/admin/_navi.html.erb
<div class="nav nav-admin">
  <span class="nav-admin title"> TestGuru Admin panel</span>

  <div class="nav-admin user">
    Welcome, <b class="nav-admin user-email"><%= current_user.email %></b> Guru |
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  </div>

</div>

app/views/shared/_badges.html.erb
<div class="row" align="right">
  <div class="col-12" style="height: 50px; padding: 5px;">
      <div class="btn">Badge 1 Badge 2 Badge 3</div>
  </div>

</div>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, resource, class: 'resource-errors', data: {resource_id: resource.id } do %>
    <h2>
        <%= t('.header', count: resource.errors.count) %>:
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message, class: "flash #{key}" %>
<% end %>

app/views/shared/_footer.html.erb
<div class="card" style="background-color: #9487a9;">
  <div class="card-header"><b> about this project </b></div>
    <div class="card-body">

      <blockquote class="blockquote mb-0">
        <footer class="blockquote-footer"><a href="author" target="_blank"> about author this project </a><br/></footer>
        <footer class="blockquote-footer"><a href="http://thinknetica.com" target="_blank"> Project was created due school www.thinknetica.com </a><br/></footer>
      </blockquote>

        Проект "Test Guru", First task in my course of "Ruby on Rails"<br/>
        Year from helper: <%= current_year %> and local time: <%= I18n.l(Time.now) %>
        <p> <%= github_url('archyfly', 'testguru') %> </p>

        <p> Test for User is admin?  <%= current_user.admin? if current_user.present? %> </p>

  </div>

<!--  <div id="carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%#= image_tag("console-one.png", {:style => "width:220px;", :class => "rounded"}) %>
      </div>
      <div class="carousel-item">
        <%#= image_tag("github-one.png", {:style => "width:220px;", :class => "rounded"}) %>
      </div>
    </div>
  <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Предыдущий</span>
  </a>
  <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Следующий</span>
  </a>
  </div>
</div>
-->

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light .bg-gradient-light" style="background-color: #7b7b9b;">

  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <a class="navbar-brand" href="#">
    <%= image_tag("console-one.png", {:style => "width:200px;", :class => "rounded"}) %>
    <%= image_tag("github-one.png", {:style => "width:260px;", :class => "rounded"}) %>
  </a>

  <span class="navbar-text">
    <% if user_signed_in? %>
      Welcome, <b><%= current_user.email %></b> Guru |
      <% if current_user.admin? %>
        <button type="submit" class="btn"><%= link_to 'Admin panel', admin_tests_path %></button>
      <% else %>
        <button type="submit" class="btn"><%= link_to 'Send your feedback', new_feedback_url %></button>
      <% end %>

      <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>

    <% else %>
      <%= link_to "Log in", new_session_path(resource_name) %>
      <%= link_to "Sign Up", new_registration_path(resource_name) %>
    <% end %>

  </span>
</nav>

app/views/shared/_navi.html.erb
<p class='flash notice' align='center'> Welcome on local project TestGuru </p>
<% if user_signed_in? %>
  <p class='flash alert' align='center'> Welcome <%= current_user.first_name %> <%= current_user.last_name %> ( <%= current_user.type %>), you logged in! </p>
  <td>
    <%= link_to 'logout', logout_path, method: :delete %>
  </td>
<% else %>
  <p class='nav user' align='center'>Проект "Test Guru"</p>
  <table align = "right">
    <td>
      <a href="/gurus/login" target="_self"> Log in </a></p><br/>
    </td>
    <td>
      <a href="/gurus/sign_up" target="_self"> Register </a></p><br/>
    </td>
  </table>
  </p>

<% end %>

app/views/shared/_timer.html.erb
<font color="green"><b>
  <div class="timeStartTest"><% time_start = Time.now %></div>
  <div class="setTestDuration"><%= @test_passage.test.test_duration %> minute for passage this test</div></b>
  <p id="timeRemaining" style="color: green"><b>Time remaining:</b><p>
  <p id="timeLeft" style="color: blue"></p>
  <div class="timeNow" style="display: none"><%= I18n.l(Time.now) %></div>
</font>

<script>
  var duration = document.querySelector('.setTestDuration').innerHTML;
  $("#timeEndTest").text(duration*60)
  var mins = duration-1;
  var secs = 60;

  $("#mins").text(mins)
  $("#secs").text(secs)

  var timerLeft = setInterval(function() {
    if (mins >= 0) {
      if (secs > 0) {
        secs -= 1
        if (mins == 0 && secs < 10) {
          $("#timeLeft").css("color", "red")
          $("#timeRemaining").css("color", "red")
          $("#timeLeft").text(mins + ':' + '0' + secs)

        }
        else {
          $("#timeLeft").text(mins + ':' + secs)
        }
      }
      else {
        mins -= 1
        secs = 60
        }
      }
    else {
      alert("You so slowly, try next time.")
      clearInterval(timerLeft);
      }
  }, 1000);
  </script>