config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  delete :logout, to: 'sessions#destroy'

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true do
      resources :answers, only: :index, shallow: true
    end

    member do
      post :start
    end

  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      # метод patch, поскольку обновляем конкретный тест - указываем опцию on: :member,
      # чтобы у нас в url был id конкретного теста

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end

  resources :gists, only: %i[index show]

  namespace :admin do
    resources :users, only: %i[index show]
  end

  namespace :admin do
    resources :gists, only: %i[index show]
  end

  namespace :admin do
    resources :badges
  end

  resources :feedbacks

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true)}

  validate :answers_from_one_to_four

  def answers_from_one_to_four
    errors.add(:question, 'has so many answers') if (question.answers.count) >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < ApplicationController
  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def index
  end

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to [:admin, @answer], notice: "Answer was successfully created."
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer), notice: "Answer was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:body, :correct)
    end

    def find_question
      @question = Question.find(params[:question_id])
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def index
  end

  def show
  end

  # def new
  #   @answer = @question.answers.new
  # end

  # def edit
  # end

  # def create
  #   @answer = @question.answers.new(answer_params)

  #   if @answer.save
  #     redirect_to @answer, notice: "Answer was successfully created."
  #   else
  #     render :new
  #   end
  # end

  # def update
  #   if @answer.update(answer_params)
  #     redirect_to @answer, notice: "Answer was successfully updated."
  #   else
  #     render :edit
  #   end
  # end

  # def destroy
  #  @answer.destroy
  #  redirect_to @answers.question
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:body, :correct)
    end

    def find_question
      @question = Question.find(params[:question_id])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %><br/>
  <%= link_to 'Show', admin_answer_path(answer) %> |
  <%= link_to 'Edit', edit_admin_answer_path(answer) %> |
  <%= link_to 'Delete',
              admin_answer_path(answer),
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>


  <p><%= form.submit %></p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', admin_answer_path %> |
<%= link_to 'Back', question_answers_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1>New Answer</h1>

<p>
  New answer for <b> question: <%= @question.title %></b>
</p>

<%= render 'form' %>
<%= link_to 'Back', question_answers_path %>

app/views/admin/answers/show.html.erb
<h1>Question</h1>

<%= @answer.question.title %>

<p>
  <b>Answer:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Edit', edit_admin_answer_path(@answer) %> |
<%= link_to 'Back', admin_question_path(@answer.question) %>