config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  delete :logout, to: 'sessions#destroy'

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true do
      resources :answers, only: :index, shallow: true
    end

    member do
      post :start
    end

  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      # метод patch, поскольку обновляем конкретный тест - указываем опцию on: :member,
      # чтобы у нас в url был id конкретного теста

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end

  resources :gists, only: %i[index show]

  namespace :admin do
    resources :users, only: %i[index show]
  end

  namespace :admin do
    resources :gists, only: %i[index show]
  end

  namespace :admin do
    resources :badges
  end

  resources :feedbacks

end

app/models/feedback.rb
class Feedback < ApplicationRecord

  belongs_to :user

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  before_action :authenticate_user!

  def index
    @feedbacks = Feedback.all
  end

  def new
    @feedback = Feedback.new
  end

  def show
    render :root
  end

  def create
    @feedback = current_user.feedbacks.new(feedback_params)
      if @feedback.save
        #FeedbacksMailer.feedback_mail(current_user, @feedback).deliver_now
        redirect_to feedbacks_url
      else
        render :new
      end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:feedback)
  end

end

app/views/feedbacks/_form.html.erb
<%= form_with model: [@feedback], local: true do |form| %>

  <p>
    <%= form.label :feedback %><br>
    <%= form.text_area :feedback, rows: 7, cols: 60 %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/feedbacks/index.html.erb
<h1 align="center"><b>Show all feedbacks</b></h1>

<table class="table table-striped table-light">
  <tr>
    <th><b>User email:</b></th>
    <th><b>feedback<b></th>
  </tr>

  <% @feedbacks.each do |fb| %>
    <tr>
      <td><%= fb.user.email %></td>
      <td><%= fb.feedback %></td>
    </tr>
  <% end %>
</table>

<br/>

app/views/feedbacks/new.html.erb
<h1>Create new feedback</h1>
<%= render 'form' %>
<%= link_to 'Back', feedbacks_path %>